### ISSUE TITLE
Error on Console

### ISSUE THREAD

**Issue by PinoyLifeCraft** [gvlfm78/BukkitOldCombatMechanics#273] opened 2019-01-24 12:30 UTC
## Info

- Server version: 1.13.2
- OldCombatMechanics version: 1.6.6

## Problem Description
> 
 Error in console. https://pastebin.com/WzjfSYNN

**Comment by gvlfm78** [comment] 2019-01-25 14:13
Duplicate of #249 #246 #245 #253 #266 #269. Please use the latest test build of OldCombatMechanics from [here](http://ci.rayzr.tech/job/OldCombatMechanics/).

**Closed by gvlfm78** 2019-01-25 14:13 UTC
