### ISSUE TITLE
Fishing rods can be used in PvP off areas

### ISSUE THREAD

**Issue by iMaarten** [gvlfm78/BukkitOldCombatMechanics#203] opened 2018-07-26 00:42 UTC
## Info
- Server version:  Paper version git-Paper-"591b2777" (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
- OldCombatMechanics version:  1.6.6
- WorldGuard version 6.2.2-SNAPSHOT;63edfbf
- Server log file: N/A
- OldCombatMechanics config file:  https://pastebin.com/ve8K3umT

## Problem Description
> Fishing rods can be used even when pvp is turned of in regions.

**Comment by Rayzr522** [comment] 2018-07-26 01:05
Is the PVP disabled in the area due to WorldGuard? If not, what plugin is disabling the PVP in that area?

**Comment by iMaarten** [comment] 2018-07-26 03:13
It is the WorldGuard pvp flag

**Comment by I-Al-Istannen** [comment] 2018-07-26 14:34
Just checking whether the event is cancelled (or setting `ignoreCancelled = true`) on the `onRodHit` listener might be enough.

**Comment by Rayzr522** [comment] 2018-07-26 14:48
Shouldn't this be as simple as firing our own EntityDamageEvent, checking if it's cancelled, and if it's not then only *then* doing damage with the fishing rod?

**Comment by I-Al-Istannen** [comment] 2018-07-26 14:50
I misread the name, they use DamageEntityEvent not EntityDamageEvent, which is their own one. Gotta have to dig deeper into that one (it can be found [here](https://github.com/sk89q/WorldGuard/blob/9cafb07e4d276eb75c1f460f288381fa17e2d7b3/worldguard-legacy/src/main/java/com/sk89q/worldguard/bukkit/listener/BlockedPotionsListener.java#L56))

**Comment by I-Al-Istannen** [comment] 2018-07-26 14:54
```diff
diff --git a/src/main/java/gvlfm78/plugin/OldCombatMechanics/module/ModuleFishingKnockback.java b/src/main/java/gvlfm78/plugin/OldCombatMechanics/module/ModuleFishingKnockback.java
index 3dde337..02745f2 100644
--- a/src/main/java/gvlfm78/plugin/OldCombatMechanics/module/ModuleFishingKnockback.java
+++ b/src/main/java/gvlfm78/plugin/OldCombatMechanics/module/ModuleFishingKnockback.java
@@ -73,6 +73,10 @@ public class ModuleFishingKnockback extends Module {
 
         EntityDamageEvent event = makeEvent(rodder, player, damage);
         Bukkit.getPluginManager().callEvent(event);
+        if(event.isCancelled()) {
+            System.out.println("NO!");
+            return;
+        }
 
         if(module().getBoolean("checkCancelled") && event.isCancelled()){

```

seems to be enough

**Comment by Rayzr522** [comment] 2018-07-26 14:55
I'll do that now :smile:

**Comment by I-Al-Istannen** [comment] 2018-07-27 09:09
@iMaarten Wait, do you really have `checkCancelled` enabled in the config (under fishing)?

If yes, can you enable the debug mode of OCM in the config and see if it sends you any message in the chat, if you rod somebody in a no-pvp area?

**Comment by I-Al-Istannen** [comment] 2018-07-27 12:54
Okay, I see the problem. You have `useEntityDamageEvent` enabled in the config and this causes OCM to (rightfully) use just that. The problem is that the pure damage event does not contain information about the attacker, so worldguard thinks it is just some damage — not that another player rodded you, but more like walking into a cactus. Logically the pvp check doesn't do anything then — it wasn't player induced damage.

Try setting this value to false and see if the error persists. If this causes errors with NCP, we will have to look into that.

**Comment by iMaarten** [comment] 2018-07-27 22:50
That fixes the WorldGuard issue, however, Only some of the hits will actually register and the whole knockback seems a bit off 
https://i.imgur.com/bc4qfOT.png <- Debug of being hit
https://www.youtube.com/watch?v=9WJYiSio0-k <- Video of hitting

**Comment by gvlfm78** [comment] 2018-07-28 10:19
IIRC `checkCancelled` is an option in the config because EssentialsX seemed to cancel the event about 3 out of 4 times it fired, for some reason I was not able to figure out.

**Comment by iMaarten** [comment] 2018-07-29 14:38
The problems seems to indeed to be EssentialsX, knockback still seems about the same.

**Comment by I-Al-Istannen** [comment] 2018-07-29 16:14
Hm. I can't reproduce it with EssentialsX. Do you need some special config settings?

Knockback is interesting though. Does this build attached here is closer to it? It's mostly equal to the knockback from 1.8.8 based on the decompiled minecraft code.
[OCM.zip](https://github.com/gvlfm78/BukkitOldCombatMechanics/files/2238950/OCM.zip)

**Comment by I-Al-Istannen** [comment] 2018-07-29 16:52
Made a small error in not removing enough of the old knockback code. This one fixes a too high Y Velocity (actually a *teleport* up) which allowed for *far* too great upwards momentum.

[OCM.zip](https://github.com/gvlfm78/BukkitOldCombatMechanics/files/2238985/OCM.zip)

But I can not reproduce the issue:

![See here](https://user-images.githubusercontent.com/20284688/43368620-6a285a76-9360-11e8-8187-8e4866c489a3.gif)

You said it was EssentialsX, is there anything else that needs to be present for you to reproduce the bug?

**Comment by gvlfm78** [comment] 2018-07-29 22:14
When I was revising this module and came across this issue it had been EssentialsX that was cancelling the event, however I don't know if that was a bug that has now been fixed or a conflict of sorts.

**Comment by iMaarten** [comment] 2018-08-09 10:57
Can not find anything else interfering.

**Comment by I-Al-Istannen** [comment] 2018-08-22 14:46
I'd love to fix that, but I can not reproduce it. EssentialsX by itself only ever cancels the EntityDamageEvent under a few special circumstances and nothing you should have had happen in that video.

So it might be another one of your plugins or some settings are different? I used your config though, which is weird.

Can you, @Rayzr522 or @gvlfm78 or anybody else reproduce it?

**Comment by I-Al-Istannen** [comment] 2018-11-05 21:21
1.12:
```java
    public Fish getHook() {
        return this.hookEntity;
    }
```

1.13:
```java
    public FishHook getHook() {
        return this.hookEntity;
    }
```

I will have a look at it tomorrow if nobody else has taken it up by then. I am way too tired right now sadly.

**Comment by Rayzr522** [comment] 2018-11-06 02:40
I don't believe it should be an issue, tho maybe we will have to manually cast the output of `e.getHook()`, as they are both implementations of `Entity`. Perhaps we just need to cast it to `Entity`?

**Comment by iMaarten** [comment] 2018-11-06 17:17
Any chance it can be fixed that players can basically fly up https://i.imgur.com/PWKd0R0.gifv

**Comment by gvlfm78** [comment] 2018-11-08 15:08
@iMaarten there is already an issue for that here: #139. I might have a look at it now.

**Comment by gvlfm78** [comment] 2018-11-08 17:32
@iMaarten I have added a configurable fishing rod knockback cooldown which appears to have fixed the issue.

To @Rayzr522 @I-Al-Istannen: however, I am not sure whether it will be an issue if the HashMap I used fills up with an entry for each player that has been on the server and hit somebody else with a fishing rod since the server start. Could become a problem for larger servers due to memory usage. Currently, the list is cleared only if the module is reloaded. Maybe scheduling tasks to clear it periodically? (If this is even an issue at all)

**Comment by I-Al-Istannen** [comment] 2018-11-08 18:07
You could have just used `Player#setNoDamageTicks` to prevent further damage within the configured delay (it is how it normally works with damaging entities --- they are granted a small period of nearly invincibility). For this to work correctly you likely need to delay applying the noDamageTick value by a tick, so do that it in a runnable that runs on the next tick.

If you really only want to prevent *rod* damage, then that sounds like a way to do it, but adding a listener to clear it out on PlayerQuitEvent should be easy and help somewhat.
Another way would be using a google guava cache and to set the expiration to the one specified in the config (though then you'd need to handle config reloads).

A cleaning task would work too, but might be a bit overkill, if you just remove them in on player quit. A Long is larger than a long (object header and such garbage), but still not incredibly so, so I am not sure if it is worth it.

The cleanest solution would be using the noDamageTicks, though that applies to all kinds of damage and not just rod usage.

**Comment by gvlfm78** [comment] 2018-11-10 23:52
@I-Al-Istannen This begs the question, in 1.8, did getting hit with a fishing rod grant you a short time of invincibility from all weapons or did it only apply to fishing rods?

**Comment by I-Al-Istannen** [comment] 2018-11-11 09:58
@gvlfm78 The concept of noDamageTicks is *old* and exists for all kinds of damage. It allowed spamming rods when using the plugin, as the plugin *did not check the noDamageTicks* and directly called `Player#damage`, which doesn't care about them.

If you add a check for noDamageTicks in the listener, it will mirror the vanilla behavior and not allow spamming it:
```java
// ....
if(player.getGameMode() == GameMode.CREATIVE) return;

// Check if cooldown time has elapsed
if(player.getNoDamageTicks() > player.getMaximumNoDamageTicks() / 2f){
    return;
}
```

**Comment by gvlfm78** [comment] 2018-11-12 10:15
@I-Al-Istannen I was asking whether noDamageTicks was used specifically with fishing rods in 1.8. If that is the case, then using noDamageTicks would be the best solution.

Furthermore, previously you stated that we should use `Player#setNoDamageTicks`, however your code diff simply compares the damage ticks but never sets them. Would that then still be sufficient?

**Comment by gvlfm78** [comment] 2018-11-21 01:52
Sorry I had forgotten about this but I have now merged your commit @I-Al-Istannen. @iMaarten please check if the issues are still there.

**Comment by Rayzr522** [comment] 2018-12-11 18:12
Please try out [the latest development build](http://ci.rayzr.tech/job/OldCombatMechanics/) and let us know if this has solved your issue. Thanks :)

**Closed** 2018-12-16 21:33 UTC
Labels: awaiting testing, bug, user vanished

**Comment by Zaino60** [comment] 2019-07-27 18:59
Bug still happening on islands pvp protected by https://www.spigotmc.org/resources/askyblock.1220/

**Comment by I-Al-Istannen** [comment] 2019-07-27 19:29
How did you configure the island? I find the plugin's protection system to be a bit confusing, as I can not find a PVP flag in the settings.
