### ISSUE TITLE
Tossing armor 'java.lang.IllegalStateException: Unable to find method getTypeId ([]).'

### ISSUE THREAD

**Issue by theonlygusti** [gvlfm78/BukkitOldCombatMechanics#299] opened 2019-04-29 16:32 UTC
Pressing 'q' on armor in armor slots in inventory caused this error

```
[17:28:51 ERROR]: Could not pass event ArmourEquipEvent to OldCombatMechanics v1.6.6
java.lang.IllegalStateException: Unable to find method getTypeId ([]).
        at com.comphenix.example.NbtFactory.getMethod(NbtFactory.java:356) ~[?:?]
        at com.comphenix.example.NbtFactory.<init>(NbtFactory.java:54) ~[?:?]
        at com.comphenix.example.NbtFactory.get(NbtFactory.java:83) ~[?:?]
        at com.comphenix.example.NbtFactory.getCraftItemStack(NbtFactory.java:207) ~[?:?]
        at com.comphenix.example.Attributes.<init>(Attributes.java:22) ~[?:?]
        at gvlfm78.plugin.OldCombatMechanics.module.ModuleOldArmourStrength.apply(ModuleOldArmourStrength.java:46) ~[?:?]
        at gvlfm78.plugin.OldCombatMechanics.module.ModuleOldArmourStrength.onArmourEquip(ModuleOldArmourStrength.java:149) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor36.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.13.2.jar:git-Paper-616]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.13.2.jar:git-Paper-616]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[patched_1.13.2.jar:git-Paper-616]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:520) ~[patched_1.13.2.jar:git-Paper-616]
        at com.codingforcookies.armourequip.ArmourListener.onInventoryClick(ArmourListener.java:147) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor14.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.13.2.jar:git-Paper-616]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.13.2.jar:git-Paper-616]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[patched_1.13.2.jar:git-Paper-616]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:520) ~[patched_1.13.2.jar:git-Paper-616]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:2287) ~[patched_1.13.2.jar:git-Paper-616]
        at net.minecraft.server.v1_13_R2.PacketPlayInWindowClick.a(SourceFile:33) ~[patched_1.13.2.jar:git-Paper-616]
        at net.minecraft.server.v1_13_R2.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.13.2.jar:git-Paper-616]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15) ~[patched_1.13.2.jar:git-Paper-616]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-616]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1018) ~[patched_1.13.2.jar:git-Paper-616]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-616]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-616]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-616]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by gvlfm78** [comment] 2019-04-29 19:06
Duplicate of #249 #246 #245 #253 #266 #269 #297. Please use the latest test build of OldCombatMechanics from [here](https://ci.rayzr.dev/job/OldCombatMechanics/).

**Closed by gvlfm78** 2019-04-29 19:06 UTC
Labels: bug, duplicate
