### ISSUE TITLE
PlayerJoinEvent

### ISSUE THREAD

**Issue by elstur** [gvlfm78/BukkitOldCombatMechanics#195] opened 2018-07-16 04:14 UTC
Using the latest dev build of Old Combat Mechanics as of July 15th, 2018
Using PaperSpigot 1.12.2 Also updated latest version as of July 15th, 2018
Using ProtocolSupport

I am now getting a new error every time someone joins that I was not getting on an older version. Not sure what changed. Here is the error:
https://pastebin.com/kBgTdFU0

**Comment by I-Al-Istannen** [comment] 2018-07-16 21:31
Can't reproduce with
```
> version
[23:29:13 INFO]: This server is running Paper version git-Paper-1500 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
[23:29:13 INFO]: Checking version, please wait...
[23:29:13 INFO]: You are running the latest version

> protocolsupport buildinfo 
[23:29:35 INFO]: protocolsupport.ProtocolSupport$BuildInfo(buildtime: 2018.06.12 at 05:27:43 MSK, buildhost: build.true-games.org, buildnumber: 239)

> ocm
[23:29:57 INFO]: ----------------------------------------------------
[23:29:57 INFO]: OldCombatMechanics by gvlfm78 and Rayzr522 version 1.6.5
[23:29:57 INFO]: You can use /ocm reload to reload the config file
[23:29:57 INFO]: -----
```

and default configs for all.

**Comment by elstur** [comment] 2018-07-16 23:13
Same version of paper and same version of protocol support. I just can't verify which build of 1.6.5 you are testing with. I was using the latest dev build #44 on the Jenkins page. If I use the release on the spigot page it works without error.

If you are also using the same build, then perhaps:
Using the latest version of Hexacord (ProtocolSupport version of BungeeCord), ProtocolSupportLegacySupport and ProtocolSupportPotions.

In any scenario, it stems from the changes between the released build of 1.6.5 and the current dev build.

**Comment by I-Al-Istannen** [comment] 2018-07-17 16:05
I am using #44 too. The change is the deeper packet inspection that rewrites all outgoing scoreboard packets in order to reliably disable collision — even if you use a scoreboard or another scoreboard plugin.

I don't really want to go through the trouble of setting up bungee (I have literally never done it), but I have installed this so far:
```
> pl
Plugins (7): AnimatedScoreboard, OldCombatMechanics, PlaceholderAPI, ProtocolLib, ProtocolSupport, ProtocolSupportLegacySupport, ProtocolSupportPotions
```

## What I tried
1. Joining with an 1.8.8 client on a 1.12 server — everything works
2. Joining with an 1.12 client on a 1.12 server — everything works
3. Having a scoreboard plugin send out packets (AnimatedScoreboard) to trigger the packet rewriting — everything works

### Problem
I still can not reproduce the error. Can you send a full list of plugins or try to find out which one introduces the error (using a local test server remove plugins and see when it stops crashing. You shouldn't need to use your real one for this, so it shouldn't impact players)?

**Comment by elstur** [comment] 2018-07-17 21:47
Made a dev server to test this behind my bungee. Turns out, the issue seems to be caused by iDisguise (latest version).

**Comment by I-Al-Istannen** [comment] 2018-07-17 21:56
Thanks!

I can reproduce it with that (the author probably had a good reason to do what he did, but it's something I didn't anticipate).

It is currently nearly midnight here, I will fix it when I find time tomorrow. It shouldn't be hard to do, but I have some things planned for tomorrow, though I should get it done in the next 24 hours.

**Comment by I-Al-Istannen** [comment] 2018-07-18 07:23
May be fixed in the commit referenced above, try building it yourself or using the attached jar please.

[OCM.zip](https://github.com/gvlfm78/BukkitOldCombatMechanics/files/2204802/OCM.zip)

**Comment by elstur** [comment] 2018-07-18 21:07
Confirmed, fixed. Thank you <3

**Closed** 2018-07-25 22:19 UTC
