### ISSUE TITLE
There seems to be a bug enabling the OCM

### ISSUE THREAD

**Issue by Twiistrz** [gvlfm78/BukkitOldCombatMechanics#226] opened 2018-08-25 03:15 UTC
## Info

- Server version: 1.12.2
- OldCombatMechanics version: 1.6.6
- Server log file: https://hastebin.com/ogujativet.rb
- OldCombatMechanics config file: https://hastebin.com/elehedinav.bash

## Problem Description
> Not sure there seems to be a bug enabling the OCM

**Comment by gvlfm78** [comment] 2018-08-25 13:39
This seems to be a duplicate of #215

**Comment by gvlfm78** [comment] 2018-08-25 13:40
This seems to be a duplicate of #215 , please answer over there.

**Closed** 2018-08-25 13:40 UTC
Labels: duplicate
