### ISSUE TITLE
NBT problem - Full armor values without armor

### ISSUE THREAD

**Issue by revkilleri** [gvlfm78/BukkitOldCombatMechanics#288] opened 2019-03-24 15:06 UTC
## Info

- Server version:  1.11.2
- OldCombatMechanics version: 1.6.6
- Server log file: without problems
- OldCombatMechanics config file: https://pastebin.com/uZWKA18S

## Problem Description
> Some players at my server has problem with armor values. They are like with full armor (bugged from previous wearing of diamond armor), but without any real piece of armor . If player take worst armor, he has still full armor. I think problem must be in NBT of player. I dont have any tools to reset this armor stats "stacked" into one account in nbt tags. Maybe it would work with fix for unequip/equip event that will check this bugged armor values at account. 

`https://imgur.com/a/0UqnEur`

NBT OF player: 
`https://pastebin.com/0yqHdSQ9`

Thank you for solution or fix. :)

**Comment by TheBlankSky2** [comment] 2019-03-24 17:09
Try changing the armor in config and turn old armor off.

**Comment by revkilleri** [comment] 2019-03-24 18:06
Thank you for response. I tried, but without any changes in this NBT of player and effect with armor. Problem is still same.

**Comment by gvlfm78** [comment] 2019-03-25 10:29
What happens if they put armour back on then take it off again?

**Comment by revkilleri** [comment] 2019-03-25 17:57
Without any change... armor value of the player is still same. With armor, or without. I tried it with iron armor... but bugged armor value override it... so it armor value is still full with armor, or without.

**Comment by gvlfm78** [comment] 2019-03-25 22:50
How are you putting on / taking off the armour? (Left-click/right-click/shift-click etc.)

**Comment by revkilleri** [comment] 2019-03-26 09:14
I tried all type of putting on and taking off iron armor, but it is without any changes in armor value.

**Comment by Rayzr522** [comment] 2019-04-15 15:14
OldCombatMechanics does modify the NBT of the player itself, only the items they are wearing. If you would like, I can add a feature to [OCMFixer](https://github.com/Rayzr522/OCMFixer) to revert the armor NBT of all your players. However, as I said, OCM does not modify player NBT, just the armor items. This issue must have been caused by another plugin.

Do you know of any plugins on your server which modify player NBT? I doubt it has anything to do with OCM, but I would be curious if it was some strange interaction between OCM and another plugin.

**Comment by revkilleri** [comment] 2019-04-16 07:32
> OldCombatMechanics does modify the NBT of the player itself, only the items they are wearing. If you would like, I can add a feature to [OCMFixer](https://github.com/Rayzr522/OCMFixer) to revert the armor NBT of all your players. However, as I said, OCM does not modify player NBT, just the armor items. This issue must have been caused by another plugin.
> 
> Do you know of any plugins on your server which modify player NBT? I doubt it has anything to do with OCM, but I would be curious if it was some strange interaction between OCM and another plugin.

It would be awesome if u add this feature to OCMFixer. If this problem is not caused by OCM, that should be plugin mythicmobs, where we are using attributes for custom leather armor, which maybe can cause this.

**Comment by Rayzr522** [comment] 2019-04-19 16:16
@revkilleri please check the issue report here: Rayzr522/OCMFixer#4

I am closing this issue report as it is now a concern of OCMFixer.

**Closed by Rayzr522** 2019-04-19 16:16 UTC
Labels: bug, not enough info

**Comment by Govindass** [comment] 2019-04-20 05:39
I had same problem with player NBT getting armor(armor bars without any armor equipped), the problem was solved after removal of OldCombatMechanics (didn't see it happening again)
