### ISSUE TITLE
Hackers throws "potion of dealth"

### ISSUE THREAD

**Issue by Terrifical** [gvlfm78/BukkitOldCombatMechanics#227] opened 2018-08-26 17:47 UTC
Server ver: 1.11.2
Error:  https://pastebin.com/62Wb0ixD

**Comment by Rayzr522** [comment] 2018-08-26 22:38
What do you mean "potion of death"? What is actually happening? And how did they get this potion?

**Comment by HairyDragonBeck** [comment] 2018-08-26 23:00
They get it from a hack called ‘Brewing Stand’ and they make a potion called ‘Splash Potion of Instant Damage II’ YeEt

**Comment by gvlfm78** [comment] 2018-08-27 10:37
@Rayzr522 I believe he means potion of damage. This issue is a duplicate of #220

**Closed by gvlfm78** 2018-08-27 10:37 UTC
