### ISSUE TITLE
1.12 Spam error

### ISSUE THREAD

**Issue by DuckCraftPvP** [gvlfm78/BukkitOldCombatMechanics#83] opened 2017-06-23 20:18 UTC
Hi, i am getting this error from your plugin: https://hastebin.com/noleqonuti.vbs

i am using paperspigot 1.12

add this line to ur plugin to fix the error: 
if (event.getRecipe() == null) return;

**Comment by gvlfm78** [comment] 2017-06-23 20:25
Duplicate of #77

**Closed by gvlfm78** 2017-06-23 20:25 UTC
Labels: duplicate
