### ISSUE TITLE
PlayerItemHeldEvent NPE

### ISSUE THREAD

**Issue by cuervito** [gvlfm78/BukkitOldCombatMechanics#209] opened 2018-07-27 14:11 UTC
```
[[11:07:03] [Server thread/ERROR]: Could not pass event PlayerItemHeldEvent to OldCombatMechanics v1.6.6
org.bukkit.event.EventException: null
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[skywars.jar:git-Paper-1513]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[skywars.jar:git-Paper-1513]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[skywars.jar:git-Paper-1513]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:527) ~[skywars.jar:git-Paper-1513]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:512) ~[skywars.jar:git-Paper-1513]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1207) ~[skywars.jar:git-Paper-1513]
	at net.minecraft.server.v1_12_R1.PacketPlayInHeldItemSlot.a(SourceFile:30) ~[skywars.jar:git-Paper-1513]
	at net.minecraft.server.v1_12_R1.PacketPlayInHeldItemSlot.a(SourceFile:8) ~[skywars.jar:git-Paper-1513]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[skywars.jar:git-Paper-1513]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_151]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_151]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) ~[skywars.jar:git-Paper-1513]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:849) ~[skywars.jar:git-Paper-1513]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[skywars.jar:git-Paper-1513]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:773) ~[skywars.jar:git-Paper-1513]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) ~[skywars.jar:git-Paper-1513]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.lang.NullPointerException
	at gvlfm78.plugin.OldCombatMechanics.module.ModuleSwordBlocking.postponeRestoring(ModuleSwordBlocking.java:258) ~[?:?]
	at gvlfm78.plugin.OldCombatMechanics.module.ModuleSwordBlocking.restore(ModuleSwordBlocking.java:244) ~[?:?]
	at gvlfm78.plugin.OldCombatMechanics.module.ModuleSwordBlocking.onHotBarChange(ModuleSwordBlocking.java:95) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor67.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[skywars.jar:git-Paper-1513]
	... 16 more
```

## Info

- Server version: 1.12 paper
- OldCombatMechanics version:  last update
- Server log file: 
- OldCombatMechanics config file: 
https://pastebin.com/LNU3WARM

## Problem Description
> 
error alert

**Comment by I-Al-Istannen** [comment] 2018-07-27 14:14
Duplicate of #205. Fixed in PR #206 and in the dev build [#53](https://jenkinsgvl-jenkins-gvl.1d35.starter-us-east-1.openshiftapps.com/job/OldCombatMechanics/53/).

Can you see if that dev build fixes the error?

**Comment by cuervito** [comment] 2018-08-03 14:37
sorry . but I put other data that I had forgotten in the report .. I did not do it as spam .. thanks. and I hope you can help me. regards

**Comment by I-Al-Istannen** [comment] 2018-08-03 14:41
Can you try the fix I commented above? Namely using the linked dev build 53 and seeing if the error persists?

If it still persists, the fix is probably not fixing things correctly ;)

**Closed** 2018-08-27 12:43 UTC
Labels: awaiting testing, user vanished
