### ISSUE TITLE
Sword + right click = McMMO machine broke

### ISSUE THREAD

**Issue by RainOfPain125** [gvlfm78/BukkitOldCombatMechanics#152] opened 2018-01-17 16:13 UTC
Right clicking with a sword gives a shield (assuming thats to make up for the fact that blocking with swords was removed?) but does not activate the McMMO ability Serreted Strikes

My full config - https://pastebin.com/Mz0wdunn

My plugins - AreaShop, Auctions, AutoSave, BlowableObsidians, BuycraftX, CFD, Chairs, ChatFeelings, ChestShop, Citizens, CombatLogX, CompatNoCheatPlus, CoreProtect, CrazyCrates, EpicRename, Essentials, EssentialsChat, FactionChat, Factions, HolographicDisplays, HolographicScoreboard, InfoBook, LimitCrafting, LuckPerms, MassiveBooks, MassiveCore, mcMMO, mcMMOAction, MessageAnnouncer, MobArena, Multiverse-Core, NoCheatPlus, OldCombatMechanics, Orebfuscator4, PerWorldInventory, PlayerHeads, PlayTime, ProtocolLib, ServerListPlus, ShulkerBlock, SilkSpawners, SimpleBackup, SuperbVote, SuperTrails, SuperVanish, Tablist, Vault, Votifier, WarningCategories, Wild, WorldEdit, WorldGuard

Server - git-Paper-1298

OldCombatMechanics version 1.6.3

**Comment by gvlfm78** [comment] 2018-01-17 19:03
Duplicate of #94 . Please add your information into that thread and explain in more detail what _should_ happen and what _does_ happen. The issue was never fixed (if fixable) because no one ever replied to me with more information...

**Closed** 2018-01-17 19:03 UTC
Labels: duplicate
