### ISSUE TITLE
ModuleShieldCrafting NPE

### ISSUE THREAD

**Issue by WilliamEstrela** [gvlfm78/BukkitOldCombatMechanics#78] opened 2017-06-14 10:34 UTC
![image](https://user-images.githubusercontent.com/5386302/27128152-d61f2636-50d3-11e7-9b61-e98bb64b397a.png)

**Comment by gvlfm78** [comment] 2017-06-15 06:42
Duplicate of #77

**Closed by gvlfm78** 2017-06-15 06:42 UTC
