### ISSUE TITLE
Could not pass event EntityDamageByEntityEvent to OldCombatMechanics v1.7.2

### ISSUE THREAD

**Issue by leoncp9** [gvlfm78/BukkitOldCombatMechanics#309] opened 2019-05-28 20:56 UTC
server version: paperspigot 1.13.2
log  error
https://pastebin.com/4zwHLqdf

**Comment by gvlfm78** [comment] 2019-05-29 08:24
Duplicate of #307

**Closed by gvlfm78** 2019-05-29 08:24 UTC
Labels: bug, duplicate
