### ISSUE TITLE
playerWeakReference or its value is null.

### ISSUE THREAD

**Issue by Carvane** [gvlfm78/BukkitOldCombatMechanics#224] opened 2018-08-17 13:37 UTC
## Info

- Server version: PaperSpigot-1.12.2-b1533
- OldCombatMechanics version: 1.6.6
- Server log file: [Netty Epoll Server IO #3/WARN]: [OldCombatMechanics] playerWeakReference or its value is null. This should NOT happen at this stage.Please report the error on github. (write@621231271)
- OldCombatMechanics config file: https://pastebin.com/kjrSALTu

## Problem Description
> Spam log

**Comment by detobel36** [comment] 2018-08-17 13:56
I thinks it's a duplicate of #200      
To you try the dev build ?

**Comment by Rayzr522** [comment] 2018-08-17 19:49
Yep, it's a duplicate. @Carvane please use [the latest dev build (57)](https://jenkinsgvl-jenkins-gvl.1d35.starter-us-east-1.openshiftapps.com/job/OldCombatMechanics/57/).

**Closed by Rayzr522** 2018-08-17 19:49 UTC
Labels: duplicate
