### ISSUE TITLE
Gapple cooldown

### ISSUE THREAD

**Issue by lucas2107** [gvlfm78/BukkitOldCombatMechanics#339] opened 2019-08-23 10:59 UTC
Hello,

I've a suggestion.

Can you add something to add a cooldown for GApples? Some PvP/Factions servers got a cooldown for GApples.

I tried to add my own plugin to do that, but it's not working with yours :/

If you add it, can you add a placeholder for the remaining time and a customizable placeholder when it's ready?

Best regards,

**Comment by gvlfm78** [comment] 2019-08-24 08:17
Duplicate of #122. Will aim to have it in the next feature update of the plugin.

**Closed** 2019-08-24 08:17 UTC
Labels: duplicate
