### ISSUE TITLE
Could not pass event PrepareItemCraftEvent to OldCombatMechanics v1.4.2

### ISSUE THREAD

**Issue by DefinePvP** [gvlfm78/BukkitOldCombatMechanics#85] opened 2017-06-27 21:34 UTC
https://pastebin.com/VSV9bpwY

I am running 1.12 on the latest version of PaperSpigot.  I have tried Spigot also, and the same errors occur.

**Comment by gvlfm78** [comment] 2017-06-28 09:00
Duplicate of #77 

I'm going to release the update now with all of the bugfixes

**Closed by gvlfm78** 2017-06-28 09:00 UTC
