### ISSUE TITLE
Disabling collisions doesn't work

### ISSUE THREAD

**Issue by Stephanech** [gvlfm78/BukkitOldCombatMechanics#166] opened 2018-02-26 03:47 UTC
The title is a little self-explanatory.
I have this in my config.yml:

`disable-player-collisions:
  # This is to disable player collision
  # This is now compatible with scoreboard and tablist-editing plugins
  enabled: true
  worlds: [Survival,kitpvp,coleccion,pvp,skyspawn,lobby,nether,ender,aventura,spawn,mapasskywars,recursos]`

But there are still collisions in all the worlds specified, how can I solve this problem?

Spigot 1.12
OldCombatMechanics 1.6.2

**Comment by gvlfm78** [comment] 2018-02-26 10:36
Do you know of any plugins on your server that might be interfering?

**Comment by gvlfm78** [comment] 2018-02-26 14:41
Also this is a potential duplicate of #160

**Comment by gvlfm78** [comment] 2018-03-10 21:49
Duplicate of #160

**Closed by gvlfm78** 2018-03-10 21:49 UTC
Labels: duplicate
