### ISSUE TITLE
Player Collision

### ISSUE THREAD

**Issue by RickIsThicc** [gvlfm78/BukkitOldCombatMechanics#167] opened 2018-03-09 21:49 UTC
I understand that this issue has been reported before, but an answer never seemed to be supplied. Essentially player collision is not disabled even though I have it disabled in the config.

Config: https://pastebin.com/qqgX257z (I have also set it so that the world space is empty, but it still didn't work).

Plugin Version: 1.6.3

Spigot Version: Spigot 1.12.2 # 131

Plugins: https://gyazo.com/d214ca1dfc5028b1a6fc9508787e9d49

**Comment by gvlfm78** [comment] 2018-03-10 21:49
Duplicate of #160

**Closed by gvlfm78** 2018-03-10 21:49 UTC
Labels: duplicate

**Comment by RickIsThicc** [comment] 2018-03-10 23:08
You never fixed the issue in the other ticket though? I'm not running paper or using viaversion.

**Comment by gvlfm78** [comment] 2018-03-11 13:51
I never got enough information to do so. This discussion should be continued over there.
