### ISSUE TITLE
Null pointer

### ISSUE THREAD

**Issue by AlekseyTitov99** [gvlfm78/BukkitOldCombatMechanics#285] opened 2019-03-12 00:04 UTC
- Server version: Paper 1.12
- OldCombatMechanics version: 1.6.6
- Error: https://pastebin.com/t7UbjnK4

## Problem Description
> Null pointer in console

**Comment by Rayzr522** [comment] 2019-03-12 00:07
I see, it looks like it might be a conflict with another plugin. Could you please post a list of what other plugins you have installed?

**Comment by AlekseyTitov99** [comment] 2019-03-12 00:41
https://prnt.sc/mwksth
https://prnt.sc/mwksv1

**Comment by AlekseyTitov99** [comment] 2019-03-12 00:41
https://prnt.sc/mwksth
https://prnt.sc/mwksv1

**Comment by I-Al-Istannen** [comment] 2019-03-12 13:13
@AlekseyTitov99 
It is not just us, based on that log excerpt:
```
[19:54:11] [pool-7-thread-1/WARN]: Exception in thread "pool-7-thread-1" java.lang.RuntimeException: java.util.NoSuchElementException: packet_handler
[19:54:11] [pool-7-thread-1/WARN]:  at org.inventivetalent.packetlistener.channel.INCChannel$1.run(INCChannel.java:33)
[19:54:11] [pool-7-thread-1/WARN]:  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[19:54:11] [pool-7-thread-1/WARN]:  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[19:54:11] [pool-7-thread-1/WARN]:  at java.lang.Thread.run(Thread.java:748)
[19:54:11] [pool-7-thread-1/WARN]: Caused by: java.util.NoSuchElementException: packet_handler
[19:54:11] [pool-7-thread-1/WARN]:  at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:1119)
[19:54:11] [pool-7-thread-1/WARN]:  at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:260)
[19:54:11] [pool-7-thread-1/WARN]:  at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:249)
[19:54:11] [pool-7-thread-1/WARN]:  at com.comphenix.protocol.injector.netty.PipelineProxy.addBefore(PipelineProxy.java:66)
[19:54:11] [pool-7-thread-1/WARN]:  at com.comphenix.protocol.injector.netty.ChannelInjector$3$1.addBefore(ChannelInjector.java:272)
[19:54:11] [pool-7-thread-1/WARN]:  at org.inventivetalent.packetlistener.channel.INCChannel$1.run(INCChannel.java:31)
[19:54:11] [pool-7-thread-1/WARN]:  ... 3 more
```
Another plugin using comphenix's injector failed as well.

Somehow your server does not add (or not yet) the relevant packet handler plugins attach to. This will cause all deeply packet related functionality (collisions might be the only thing) to stop working. As a workaround, you could try disabling that feature in your OCM config.

But the problem is somewhere with your server. Can you post the exact version? I think `/version` outputs that.

**Comment by AlekseyTitov99** [comment] 2019-03-12 23:16
https://prnt.sc/mx1zcv thats the exact version

**Comment by I-Al-Istannen** [comment] 2019-03-13 09:10
Alright, I tried this now:
```
[10:08:01 INFO]: This server is running Paper version git-Paper-1606 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
[10:08:01 INFO]: Checking version, please wait...
[10:08:01 INFO]: You are running the latest version
```

I can not reproduce it, so it is indeed something else on your server interfering with OCM and the other plugin.

Can you tell me the steps you need to do to reproduce the error or is it essentially random? Does it happen everytime?

**Comment by Rayzr522** [comment] 2019-04-15 15:15
Seeing as there hasn't been a response on this in over a month, I am closing it until there are any further developments.

**Closed by Rayzr522** 2019-04-15 15:15 UTC
Labels: incompatibility, user vanished
