### ISSUE TITLE
Pre-1.9 Async-Smooth Hit Detection!

### ISSUE THREAD

**Issue by FrenzyCake** [gvlfm78/BukkitOldCombatMechanics#117] opened 2017-08-17 00:50 UTC
SmashHit features for better Hit Detection (Async Hit Detection), you can read all its info right here: https://github.com/Speentie8081/SmashHit

**Comment by gvlfm78** [comment] 2017-08-18 12:12
Duplicate of #19

**Closed by gvlfm78** 2017-08-18 12:12 UTC
Labels: duplicate
