### ISSUE TITLE
Console errors

### ISSUE THREAD

**Issue by SirLuciferino** [gvlfm78/BukkitOldCombatMechanics#300] opened 2019-05-08 21:50 UTC
- Server version: 1.13.2 Paper
- OldCombatMechanics version: v1.6.6
- Server log file: https://pastebin.com/97N99K9s
- OldCombatMechanics config file: https://pastebin.com/LCtcTKKs

Problem Description
> We have detected that when a player connects this error jumps, while they are connected the error jumps but for no apparent reason.
The error is missing with the default and custom config

**Comment by gvlfm78** [comment] 2019-05-10 11:50
Duplicate of #249 #246 #245 #253 #266 #269 #297 #299. Please use the latest test build of OldCombatMechanics from [here](https://ci.rayzr.dev/job/OldCombatMechanics/).

**Closed by gvlfm78** 2019-05-10 11:50 UTC
