### ISSUE TITLE
Error found

### ISSUE THREAD

**Issue by DuckCraftPvP** [gvlfm78/BukkitOldCombatMechanics#79] opened 2017-06-16 17:10 UTC
Hi, I found this error:

https://hastebin.com/onapiwucih.vbs

**Comment by Rayzr522** [comment] 2017-06-16 18:42
Duplicate of #77.

**Closed by Rayzr522** 2017-06-16 18:42 UTC

**Comment by DuckCraftPvP** [comment] 2017-06-16 20:35
The exact cause is when u move armour around in ur inventory.
