### ISSUE TITLE
Unable to find method getTypeId()

### ISSUE THREAD

**Issue by Caleblyn** [gvlfm78/BukkitOldCombatMechanics#253] opened 2018-11-11 22:09 UTC
Here is the code
```
[14:00:08 INFO]: UUID of player TheSpeedyCreeper is 86f94215-7c52-4a55-85ab-d723f60f10a6
[14:00:08 ERROR]: Could not pass event PlayerJoinEvent to OldCombatMechanics v1.6.6
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[craftbukkit.jar:git-Bukkit-3359cb1]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit.jar:git-Bukkit-3359cb1]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [craftbukkit.jar:git-Bukkit-3359cb1]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [craftbukkit.jar:git-Bukkit-3359cb1]
        at net.minecraft.server.v1_13_R2.PlayerList.onPlayerJoin(PlayerList.java:328) [craftbukkit.jar:git-Bukkit-3359cb1]
        at net.minecraft.server.v1_13_R2.PlayerList.a(PlayerList.java:148) [craftbukkit.jar:git-Bukkit-3359cb1]
        at net.minecraft.server.v1_13_R2.LoginListener.b(LoginListener.java:122) [craftbukkit.jar:git-Bukkit-3359cb1]
        at net.minecraft.server.v1_13_R2.LoginListener.Y_(LoginListener.java:54) [craftbukkit.jar:git-Bukkit-3359cb1]
        at net.minecraft.server.v1_13_R2.NetworkManager.a(NetworkManager.java:222) [craftbukkit.jar:git-Bukkit-3359cb1]
        at net.minecraft.server.v1_13_R2.ServerConnection.c(SourceFile:171) [craftbukkit.jar:git-Bukkit-3359cb1]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:914) [craftbukkit.jar:git-Bukkit-3359cb1]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:382) [craftbukkit.jar:git-Bukkit-3359cb1]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:796) [craftbukkit.jar:git-Bukkit-3359cb1]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:699) [craftbukkit.jar:git-Bukkit-3359cb1]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
Caused by: java.lang.IllegalStateException: Unable to find method getTypeId ([]).
        at com.comphenix.example.NbtFactory.getMethod(NbtFactory.java:356) ~[?:?]
        at com.comphenix.example.NbtFactory.<init>(NbtFactory.java:54) ~[?:?]
        at com.comphenix.example.NbtFactory.get(NbtFactory.java:83) ~[?:?]
        at com.comphenix.example.NbtFactory.getCraftItemStack(NbtFactory.java:207) ~[?:?]
        at com.comphenix.example.Attributes.<init>(Attributes.java:22) ~[?:?]
        at gvlfm78.plugin.OldCombatMechanics.module.ModuleOldArmourStrength.apply(ModuleOldArmourStrength.java:46) ~[?:?]
        at gvlfm78.plugin.OldCombatMechanics.module.ModuleOldArmourStrength.setArmourAccordingly(ModuleOldArmourStrength.java:197) ~[?:?]
        at gvlfm78.plugin.OldCombatMechanics.module.ModuleOldArmourStrength.setArmourAccordingly(ModuleOldArmourStrength.java:181) ~[?:?]
        at gvlfm78.plugin.OldCombatMechanics.module.ModuleOldArmourStrength.onPlayerJoin(ModuleOldArmourStrength.java:158) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_181]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_181]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_181]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298) ~[craftbukkit.jar:git-Bukkit-3359cb1]
        ... 14 more

```

This issue is persistent. I have looked through the other posts about this issue but I still cant fix it. Can someone PLEASE help me!

**Comment by I-Al-Istannen** [comment] 2018-11-11 22:56
Are you using the newest (or nearly newest, I think you have one or two builds buffer) version from [here](http://ci.rayzr.tech/job/OldCombatMechanics/)?

If yes, please state which. If not, please try it :)

**Comment by gvlfm78** [comment] 2018-11-12 10:11
Duplicate of #249 #246 #245. Please use the latest test build of OldCombatMechanics from [here](http://ci.rayzr.tech/job/OldCombatMechanics/).

**Closed by gvlfm78** 2018-11-12 10:11 UTC
Labels: awaiting testing, bug, duplicate
