### ISSUE TITLE
NoClassDefFoundError EnchantmentType on player damage

### ISSUE THREAD

**Issue by Yokaos** [gvlfm78/BukkitOldCombatMechanics#333] opened 2019-08-09 12:58 UTC
## Info

- Server version: Spigot 1.9.2 R0.1
- OldCombatMechanics version: 1.7.3
- Server log file: https://pastebin.com/raw/48JwMYNe
- OldCombatMechanics config file: https://pastebin.com/raw/bFbkCX9z

## Problem Description
> 
I get this error every time a player takes damages.

**Comment by gvlfm78** [comment] 2019-08-10 09:05
I believe this may be the same issue as #313, which has been fixed in the beta builds. Please try a [test build](https://ci.rayzr.dev/job/OldCombatMechanics/) from the Jenkins server and see if the issue is still there.

**Closed** 2019-08-23 10:26 UTC
Labels: bug, duplicate
