### ISSUE TITLE
Incompatibility with RandomPackage

### ISSUE THREAD

**Issue by LavRad** [gvlfm78/BukkitOldCombatMechanics#282] opened 2019-02-15 16:53 UTC
## Info

- Server version: 1.13.2
- OldCombatMechanics version: 1.7.0
- Server log file: http://prntscr.com/mllc66
- OldCombatMechanics config file: 
`https://pastebin.com/w79MkNVu`

## Problem Description
>

**Comment by gvlfm78** [comment] 2019-02-21 17:36
Duplicate of #276

**Closed by gvlfm78** 2019-02-21 17:36 UTC
