### ISSUE TITLE
IllegalStateException after player join

### ISSUE THREAD

**Issue by Kamilkime** [gvlfm78/BukkitOldCombatMechanics#269] opened 2019-01-19 23:06 UTC
## Info
- Server version: 1.13.2
- OldCombatMechanics version: 1.6.6
- Server log file: error given below
- OldCombatMechanics config file: https://pastebin.com/FRXmG3qs

## Problem Description
```java
[22:31:16] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to OldCombatMechanics v1.6.6
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:309) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-7fc66b2]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-7fc66b2]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.13.2.jar:git-Spigot-f56e2e7-7fc66b2]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.13.2.jar:git-Spigot-f56e2e7-7fc66b2]
	at net.minecraft.server.v1_13_R2.PlayerList.onPlayerJoin(PlayerList.java:343) [spigot-1.13.2.jar:git-Spigot-f56e2e7-7fc66b2]
	at net.minecraft.server.v1_13_R2.PlayerList.a(PlayerList.java:162) [spigot-1.13.2.jar:git-Spigot-f56e2e7-7fc66b2]
	at net.minecraft.server.v1_13_R2.LoginListener.b(LoginListener.java:149) [spigot-1.13.2.jar:git-Spigot-f56e2e7-7fc66b2]
	at net.minecraft.server.v1_13_R2.LoginListener.tick(LoginListener.java:53) [spigot-1.13.2.jar:git-Spigot-f56e2e7-7fc66b2]
	at net.minecraft.server.v1_13_R2.NetworkManager.a(NetworkManager.java:230) [spigot-1.13.2.jar:git-Spigot-f56e2e7-7fc66b2]
	at net.minecraft.server.v1_13_R2.ServerConnection.c(ServerConnection.java:119) [spigot-1.13.2.jar:git-Spigot-f56e2e7-7fc66b2]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:994) [spigot-1.13.2.jar:git-Spigot-f56e2e7-7fc66b2]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar:git-Spigot-f56e2e7-7fc66b2]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [spigot-1.13.2.jar:git-Spigot-f56e2e7-7fc66b2]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [spigot-1.13.2.jar:git-Spigot-f56e2e7-7fc66b2]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.lang.IllegalStateException: Unable to find method getTypeId ([]).
	at com.comphenix.example.NbtFactory.getMethod(NbtFactory.java:356) ~[?:?]
	at com.comphenix.example.NbtFactory.<init>(NbtFactory.java:54) ~[?:?]
	at com.comphenix.example.NbtFactory.get(NbtFactory.java:83) ~[?:?]
	at com.comphenix.example.NbtFactory.getCraftItemStack(NbtFactory.java:207) ~[?:?]
	at com.comphenix.example.Attributes.<init>(Attributes.java:22) ~[?:?]
	at gvlfm78.plugin.OldCombatMechanics.module.ModuleOldArmourStrength.apply(ModuleOldArmourStrength.java:46) ~[?:?]
	at gvlfm78.plugin.OldCombatMechanics.module.ModuleOldArmourStrength.setArmourAccordingly(ModuleOldArmourStrength.java:197) ~[?:?]
	at gvlfm78.plugin.OldCombatMechanics.module.ModuleOldArmourStrength.setArmourAccordingly(ModuleOldArmourStrength.java:181) ~[?:?]
	at gvlfm78.plugin.OldCombatMechanics.module.ModuleOldArmourStrength.onPlayerJoin(ModuleOldArmourStrength.java:158) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-7fc66b2]
	... 14 more
```

**Comment by gvlfm78** [comment] 2019-01-21 22:32
Duplicate of #249 #246 #245 #253 #266. Please use the latest test build of OldCombatMechanics from [here](https://ci.rayzr.tech/job/OldCombatMechanics/).

**Closed by gvlfm78** 2019-01-21 22:32 UTC
Labels: bug, duplicate
