### ISSUE TITLE
Could not pass event PlayerJoinEvent to OldCombatMechanics v1.6.6

### ISSUE THREAD

**Issue by theonlygusti** [gvlfm78/BukkitOldCombatMechanics#297] opened 2019-04-22 14:17 UTC
## Info

- Server version:  Paper version git-Paper-616 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
- OldCombatMechanics version: 1.6.6 (https://www.spigotmc.org/resources/oldcombatmechanics-disable-1-9-hit-cooldown.19510/download?version=231746)
- Server log file: https://gist.github.com/theonlygusti/cba4c2882a2762733d365524dbb96cf7
- OldCombatMechanics config file: https://gist.github.com/theonlygusti/c6acee8d04e6fe9a05b10910aaec5d6e

## Problem Description
I didn't start getting this error until today (been running the server for a few weeks), have no idea what might have caused it.

**Comment by Rayzr522** [comment] 2019-04-22 21:11
Duplicate of #246. Please use [build 35 from our Jenkins build server](https://ci.rayzr.dev/job/OldCombatMechanics/35/).

A new version with the patch for this will be released soon, we are just finishing some 1.13 compatibility updates to better integrate with 1.13+.

**Closed by Rayzr522** 2019-04-22 21:11 UTC
