### ISSUE TITLE
Console Spam Error.

### ISSUE THREAD

**Issue by AdvancedGP** [gvlfm78/BukkitOldCombatMechanics#298] opened 2019-04-24 22:16 UTC
## Info

- Server version: 1.13.2
- OldCombatMechanics version: 1.6.6
- Server log file: default
- OldCombatMechanics config file: default 

## Problem Description
> my console is being spammed by a large error message
https://pastebin.com/y8ZjTjhy

**Comment by VaiTon** [comment] 2019-04-25 09:49
> Caused by: java.lang.IllegalStateException: Unable to find method getTypeId ([]).

Apparently in the server jar you are using the method `getTypeId` is missing. It has been deprecated long time ago so I'm going to look into this.

**Comment by VaiTon** [comment] 2019-04-25 10:03
@AdvancedGP Could you please try to use the latest dev build? You can find it [here](https://ci.rayzr.dev/job/OldCombatMechanics/).
Don't forget to make a backup of your server before!

**Comment by gvlfm78** [comment] 2019-04-28 12:22
Duplicate of #249 #246 #245 #253 #266 #269 #273. Please use the latest test build of OldCombatMechanics from [here](https://ci.rayzr.dev/job/OldCombatMechanics/).

**Closed by gvlfm78** 2019-04-28 12:22 UTC
