### ISSUE TITLE
Gapples not giving saturation

### ISSUE THREAD

**Issue by Clijmart** [gvlfm78/BukkitOldCombatMechanics#138] opened 2017-11-06 21:30 UTC
Whenever you lose hunger and eat a gapple to refill it, it adds the 2 hunger bars like it should, but does not add to your saturation. This means whenever you walk or anything after that, you will lose hunger rightaway.
This is quite annoying where you'd have to eat both gapples and normal food midfight, to regenerate your health enough.

**Comment by gvlfm78** [comment] 2017-11-07 09:24
Can you try disabling separately the golden apples module and the player regen module and see if the problem is still present with either disabled?

**Comment by Clijmart** [comment] 2017-11-11 19:57
After some extra testing, we wrote down these:

When both the gapples and regen are enabled, it's broken.
When the gapples are off and the regen on, the hunger part works, but ofcourse the gapples aren't cuz disabled.
When gapples are on and the regen off, it doesn't work. Hunger goes down quickly.
When both are off, the hunger part works again.

After some more testing, we noticed it's only broken when you've lost health. When it tries to regenerate, it drains your hunger, even right after you gappled.
After you eat anything else, like steak or fish, it does fill your saturation however. So it's clearly something with the gapples / regeneration.

Hope this helped :)

**Comment by gvlfm78** [comment] 2017-11-12 16:47
Ok that's great to have such informatyion already so I can just concentrate on fixing the bug itself instead of working out what's going wrong. As soon as I have time I will fix this. Please ping me in a few weeks if I forget about it.

**Comment by Clijmart** [comment] 2017-12-03 12:36
You forgot about it? :P

**Comment by gvlfm78** [comment] 2017-12-07 18:49
Well actually, I do not currently have time to work on this

**Comment by gvlfm78** [comment] 2017-12-09 15:14
Ok @Clijmart I have managed to generate some time out of nowhere and work on this. I believe it is now fixed in [test build 17](https://jenkinsgvl-jenkins-gvl.1d35.starter-us-east-1.openshiftapps.com/job/OldCombatMechanics/17/). Please try the build and confirm so I can release the fix.

**Comment by Clijmart** [comment] 2017-12-09 20:08
Thanks a lot :)
We tested quite a bit, works perfectly!
Took us some time to notice why the configs kept resetting, we didn't update the config version to 25 :>

Awesome man <3

**Closed** 2017-12-09 20:10 UTC
Labels: bug
