### ISSUE TITLE
Could not pass event Issue

### ISSUE THREAD

**Issue by CocutOu** [gvlfm78/BukkitOldCombatMechanics#301] opened 2019-05-11 04:52 UTC
- Server version: Spigot 1.13.2
- OldCombatMechanics version: 1.6.6
- Server log file: https://pastebin.com/0krhJfVW
- OldCombatMechanics config file: Default

## Problem Description
> So whenever I tried to do an event, for example, equipping armor,  join, and leave. It gives me an "Could not pass event" problem. This is my first time loading OCM, so I have not changed the config. 

**List of Plugins:** EssentialsX, Holographic Displays, KeepChunks, Multiverse Core, NTE, OCM, PEX, Plugman, ProtocolLib, Titlemanager, Vault, Worldedit, Worldguard.

**Comment by bqstnm** [comment] 2019-05-12 05:25
I have not configured my plugin either. I have a similar problem, here is my pastebin. https://pastebin.com/EmCfTYme
I get errors when I connect and disconnect with armor and also sometimes during combat. 

[22:24:41 INFO]: Plugins (30): AddLight*, Banknotes*, DiscordSRV, EasyBackup*, Essentials, EssentialsSpawn*, Factions, HolographicDisplays, KeepChunks, LuckPerms*,
 mcMMO, ObsidianDestroyer*, OldCombatMechanics*, Orebfuscator4, PlaceholderAPI, PlayerHeads*, PlayerVaults, PlayerVaultsGUI, ProtocolLib*, SilkSpawners, TabList*, 
Trading*, Vault*, Votifier, VotingPlugin, Wild, WorldBorder, WorldEdit, WorldGuard, WorldGuardExtraFlags*

**Comment by gvlfm78** [comment] 2019-05-14 12:45
Duplicate of #249 #246 #245 #253 #266 #269 #297 #299. Please use the latest test build of OldCombatMechanics from [here](https://ci.rayzr.dev/job/OldCombatMechanics/).

**Closed by gvlfm78** 2019-05-14 12:45 UTC
Labels: bug, duplicate
