### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Valentyn72** [gvlfm78/BukkitOldCombatMechanics#270] opened 2019-01-20 16:05 UTC
Error message in my console : [Netty Epoll Server IO #1/WARN]: [OldCombatMechanics] playerWeakReference or its value is null. This should NOT happen at this stage.Please report the error on github. (read)

How to solve the problem?

- Server version: 1.12
- OldCombatMechanics version: 1.6.6
- config : https://pastebin.com/B8ZhpV44

**Comment by gvlfm78** [comment] 2019-01-21 22:33
Duplicate of #248. Please use the latest test version from [here](https://ci.rayzr.tech/job/OldCombatMechanics/).

**Closed by gvlfm78** 2019-01-21 22:33 UTC
Labels: bug, duplicate
