### ISSUE TITLE
Could not pass event EntityDamageEvent to OldCombatMechanics v1.7.3

### ISSUE THREAD

**Issue by xtinadaily** [gvlfm78/BukkitOldCombatMechanics#313] opened 2019-06-09 03:56 UTC
## Info

- Server version: 1.9.4
- OldCombatMechanics version: v1.7.3
- Server log file: https://pastebin.com/C16ntBtY
- OldCombatMechanics config file: https://pastebin.com/7Vf3XHcg

## Problem Description
> Players using custom enchant weapons, armours  when fighting this error spamming in console (Crazy enchantments)

**Comment by gvlfm78** [comment] 2019-06-09 09:55
Duplicate of #312

**Closed by gvlfm78** 2019-06-09 09:55 UTC
