### ISSUE TITLE
Error in Console

### ISSUE THREAD

**Issue by ItzSheldor** [gvlfm78/BukkitOldCombatMechanics#266] opened 2019-01-08 15:44 UTC
## Info

- Server version: 1.13.2 (spigot)
- OldCombatMechanics version: 1.6.6
- Server log file: https://gist.github.com/ItzSheldor/a5ffece078ed1d336918b8eeb457d6ec
- OldCombatMechanics config file: the default

## Problem Description
> in the Console there are some errors

**Comment by gvlfm78** [comment] 2019-01-09 09:52
Duplicate of #249 #246 #245 #253. Please use the latest test build of OldCombatMechanics from [here](http://ci.rayzr.tech/job/OldCombatMechanics/).

**Closed by gvlfm78** 2019-01-09 09:52 UTC
