### ISSUE TITLE
Could not pass event PlayerJoinEvent 1.13.2

### ISSUE THREAD

**Issue by MamaBeau** [gvlfm78/BukkitOldCombatMechanics#295] opened 2019-04-10 16:33 UTC
- Server version: 1.13.2 Paper-Spigot
- OldCombatMechanics version: 1.6.6
- Server log file: Server Startup too long to put in a paste.
- OldCombatMechanics config file: https://hastebin.com/tasamacima.bash

## Problem Description
> https://hastebin.com/ewahacecak

**Comment by Rayzr522** [comment] 2019-04-15 15:07
Looks like a duplicate of #211. Please try the latest development version (#35 as of today) from our Jenkins server: [here](https://ci.rayzr.dev/job/OldCombatMechanics/35).

You can re-open the issue if the problem persists with the dev version, but this newer version has fixed the problem for everyone else that has reported this issue.

**Closed by Rayzr522** 2019-04-15 15:07 UTC
