### ISSUE TITLE
Offhand item duplication

### ISSUE THREAD

**Issue by tantanpro1612** [gvlfm78/BukkitOldCombatMechanics#163] opened 2018-02-11 16:08 UTC
I have a video to see the problem ( Hold items and open inventory, put items in offhand and close inventory, again we open inventory. Then there will be a copy of the items )
https://youtu.be/AoqxB6ZvrQA
I use paper spigot:  1.10.2 & OCM latest

**Comment by gvlfm78** [comment] 2018-02-11 19:24
So what exactly are you doing clicking-wise? Are you closing the inventory immediately after clicking into the offhand slot?

**Comment by tantanpro1612** [comment] 2018-02-12 07:14
After I clicked the item on the offhand. I immediately close inventory

**Comment by tantanpro1612** [comment] 2018-02-12 07:20
Another way, you can try clicking constantly a items put in offhand and immediately close inventory. It will produce the same result as in the video.

**Comment by I-Al-Istannen** [comment] 2018-05-07 17:58
@tantanpro1612 I can reproduce it, but the duplication is purely client side. Can you drop the items and pick them back up or relog?

**Closed** 2018-06-25 14:21 UTC
Labels: bug, user vanished

**Comment by dryter97** [comment] 2020-07-11 11:23
in reality could you reopen this one i can totaly dupe it from both client and server side making us able to legitly dupe item and sell them. mostly with armor in offhand and trying to shield when you hold a sword it will equip the armor and shield after. when its removing the fake shield its giving you back the copy of the armor in your offhand leaving you an equiped version of it into your equipment slot.
