### ISSUE TITLE
fix this error

### ISSUE THREAD

**Issue by cuervito** [gvlfm78/BukkitOldCombatMechanics#214] opened 2018-08-02 23:01 UTC
## Info

- Server version: Paper version git-Paper-1524 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
- OldCombatMechanics version: 1.6.6
- Server log file: 
https://pastebin.com/Wni4LPVw
- OldCombatMechanics config file: 
https://pastebin.com/aZhX5MBR

## Problem Description
> error in console

**Comment by I-Al-Istannen** [comment] 2018-08-03 08:51
https://github.com/gvlfm78/BukkitOldCombatMechanics/issues/209#issuecomment-408431344

**Comment by gvlfm78** [comment] 2018-08-07 07:47
Duplicate of #209

**Closed by gvlfm78** 2018-08-07 07:47 UTC
Labels: duplicate
