### ISSUE TITLE
Error on 1.13.2 (PaperSpigot)

### ISSUE THREAD

**Issue by cloakfox** [gvlfm78/BukkitOldCombatMechanics#261] opened 2018-12-29 11:00 UTC
https://pastebin.com/VfEzidst

PaperSpigot build: 481
OldCombatMechanics version: 1.6.6

**Comment by I-Al-Istannen** [comment] 2018-12-29 11:47
This issue was reported quite a few times (the first seems to be #229) and it was fixed in #230 a few months ago.

Please use a newer version of OCM (either from [the jenkins server](https://github.com/gvlfm78/BukkitOldCombatMechanics/issues/229) or the other download sites linked in the readme).

**Comment by Rayzr522** [comment] 2018-12-29 11:47
Please try the latest dev build here: http://ci.rayzr.tech/job/OldCombatMechanics/28/

I believe this is a duplicate of #229.

**Closed** 2018-12-29 11:51 UTC
