### ISSUE TITLE
PlayerWeakReference

### ISSUE THREAD

**Issue by ZoneTriplu** [gvlfm78/BukkitOldCombatMechanics#252] opened 2018-11-10 17:09 UTC
## Info

- Server version: 
- OldCombatMechanics version: 
- Server log file: 
- OldCombatMechanics config file: 

## Problem Description
> 
[18:02:54] [Netty Epoll Server IO #0/WARN]: [OldCombatMechanics] playerWeakReference or its value is null. This should NOT happen at this stage.Please report the error on github. (write@1669532534)
[18:02:54] [Netty Epoll Server IO #0/WARN]: [OldCombatMechanics] playerWeakReference or its value is null. This should NOT happen at this stage.Please report the error on github. (write@1669532534)
[18:02:54] [Netty Epoll Server IO #0/WARN]: [OldCombatMechanics] playerWeakReference or its value is null. This should NOT happen at this stage.Please report the error on github. (write@1669532534)
[18:02:54] [Netty Epoll Server IO #0/WARN]: [OldCombatMechanics] playerWeakReference or its value is null. This should NOT happen at this stage.Please report the error on github. (write@1669532534)
[18:02:54] [Netty Epoll Server IO #0/WARN]: [OldCombatMechanics] playerWeakReference or its value is null. This should NOT happen at this stage.Please report the error on github. (write@1669532534)
[18:02:54] [Netty Epoll Server IO #0/WARN]: [OldCombatMechanics] playerWeakReference or its value is null. This should NOT happen at this stage.Please report the error on github. (write@1669532534)
[18:02:54] [Netty Epoll Server IO #0/WARN]: [OldCombatMechanics] playerWeakReference or its value is null. This should NOT happen at this stage.Please report the error on github. (write@1669532534)
[18:02:54] [Netty Epoll Server IO #0/WARN]: [OldCombatMechanics] playerWeakReference or its value is null. This should NOT happen at this stage.Please report the error on github. (write@1669532534)
[18:02:54] [Netty Epoll Server IO #0/WARN]: [OldCombatMechanics] playerWeakReference or its value is null. This should NOT happen at this stage.Please report the error on github. (write@1669532534)
[18:02:54] [Netty Epoll Server IO #0/WARN]: [OldCombatMechanics] playerWeakReference or its value is null. This should NOT happen at this stage.Please report the error on github. (write@1669532534)
[18:02:54] [Netty Epoll Server IO #0/WARN]: [OldCombatMechanics] playerWeakReference or its value is null. This should NOT happen at this stage.Please report the error on github. (write@1669532534)
[18:02:54] [Netty Epoll Server IO #0/WARN]: [OldCombatMechanics] playerWeakReference or its value is null. This should NOT happen at this stage.Please report the error on github. (write@1669532534)
[18:02:54] [Netty Epoll Server IO #0/WARN]: [OldCombatMechanics] playerWeakReference or its value is null. This should NOT happen at this stage.Please report the error on github. (write@1669532534)
[18:02:54] [Netty Epoll Server IO #0/WARN]: [OldCombatMechanics] playerWeakReference or its value is null. This should NOT happen at this stage.Please report the error on github. (write@1669532534)
[18:02:54] [Netty Epoll Server IO #0/WARN]: [OldCombatMechanics] playerWeakReference or its value is null. This should NOT happen at this stage.Please report the error on github. (write@1669532534)
[18:02:54] [Netty Epoll Server IO #0/WARN]: [OldCombatMechanics] playerWeakReference or its value is null. This should NOT happen at this stage.Please report the error on github. (write@1669532534)
[18:02:54] [Netty Epoll Server IO #0/WARN]: [OldCombatMechanics] playerWeakReference or its value is null. This should NOT happen at this stage.Please report the error on github. (write@1669532534)
[18:02:54] [Netty Epoll Server IO #0/WARN]: [OldCombatMechanics] playerWeakReference or its value is null. This should NOT happen at this stage.Please report the error on github. (write@1669532534)
[18:02:54] [Netty Epoll Server IO #0/WARN]: [OldCombatMechanics] playerWeakReference or its value is null. This should NOT happen at this stage.Please report the error on github. (write@1669532534)
[18:02:54] [Netty Epoll Server IO #0/WARN]: [OldCombatMechanics] playerWeakReference or its value is null. This should NOT happen at this stage.Please report the error on github. (write@1669532534)
[18:02:54] [Netty Epoll Server IO #0/WARN]: [OldCombatMechanics] playerWeakReference or its value is null. This should NOT happen at this stage.Please report the error on github. (write@1669532534)
[18:02:54] [Netty Epoll Server IO #0/WARN]: [OldCombatMechanics] playerWeakReference or its value is null. This should NOT happen at this stage.Please report the error on github. (write@1669532534)

**Comment by gvlfm78** [comment] 2018-11-10 23:48
Duplicate of #248

**Closed by gvlfm78** 2018-11-10 23:48 UTC
