### ISSUE TITLE
1.13 unable to find method getTypeId

### ISSUE THREAD

**Issue by zenandreas** [gvlfm78/BukkitOldCombatMechanics#249] opened 2018-10-21 20:46 UTC
## Info

- Server version: 1.13 latest buildtools
- OldCombatMechanics version: latest from spigot
- Server log file: https://hastebin.com/sawetuqiho.md
- OldCombatMechanics config file: untouched,default config

## Problem Description
> there isn't a problem that i notice ingame, just a console error.

**Comment by I-Al-Istannen** [comment] 2018-10-21 20:48
#### For the sake of bookkeeping:
It sounds like a duplicate of #246 which is a duplicate of #229 which was fixed in PR #230, merged at the 5th of September.

#### For you:
This error was fixed in a development build a while ago.
Please try a dev build from [here](http://ci.rayzr.tech/job/OldCombatMechanics/) and report back, if this does not resolve the error for you.

**Closed** 2018-11-08 14:54 UTC
Labels: awaiting testing, bug
